#!/bin/bash

gross()
{	
	da=$(echo "scale=2;(0.10*$1)" | bc)
	ta=$(echo "scale=2;(0.12*$1)" | bc)
	gr=$(echo "scale=2;($da+$ta+$1)" | bc)
	echo "Your gross salary is $gr"
}


if [ $# -eq 0 ]
then
	read -p "Enter your basic salary " s
	gross $s
else
	gross $1
fi
